// SEO Keyword Bank for NexusVault
// Organized by category for targeted page-level injection

export const SEO_KEYWORDS = {

  // --- Brand & Platform Identity ---
  brand: [
    "NexusVault", "NexusVault platform", "NexusVault code hosting", "NexusVault repositories",
    "NexusVault developer platform", "NexusVault source control", "NexusVault IDE",
    "NexusVault collaboration", "NexusVault version control", "NexusVault git alternative",
  ],

  // --- GitHub Alternatives (High Traffic) ---
  githubAlternative: [
    "github alternative", "github alternative 2025", "best github alternative", "free github alternative",
    "open source github alternative", "self hosted github alternative", "github competitor",
    "alternatives to github", "gitlab alternative", "bitbucket alternative", "gitea alternative",
    "forgejo alternative", "sourcehut alternative", "codeberg alternative", "azure devops alternative",
    "github replacement", "code hosting alternative", "repository hosting alternative",
    "developer platform alternative", "git hosting alternative", "private git hosting",
    "github like platform", "github clone open source", "github for teams",
    "github for startups", "github for enterprise", "github for freelancers",
    "github for small business", "github for solo developers", "github for designers",
    "github for data scientists", "github for game developers", "github for non coders",
    "is github the same as git", "github vs gitlab", "github vs bitbucket",
    "github vs gitea", "github vs sourcehut", "github vs azure devops",
    "github vs nexusvault", "best code hosting platform", "best repository hosting 2025",
  ],

  // --- Version Control Core ---
  versionControl: [
    "version control", "version control system", "version control software", "version control tool",
    "what is version control", "why use version control", "version control benefits",
    "version control for beginners", "version control tutorial", "version control guide",
    "version control best practices", "version control workflow", "version control for teams",
    "version control for small teams", "version control for startups", "version control for enterprise",
    "version control for freelancers", "version control for solo developers",
    "version control for non-technical teams", "version control for designers",
    "version control for data scientists", "version control for game developers",
    "version control for artists", "version control for writers", "version control for creative teams",
    "version control mistakes", "version control red flags", "version control pitfalls",
    "version control migration", "migrating to version control", "transition to version control",
    "manual file versioning vs version control", "version control vs backup",
    "version control certification", "version control career", "version control interview",
    "version control job requirement", "learn version control", "version control learning curve",
    "how long to learn version control", "version control for students",
    "version control without command line", "git gui client", "version control GUI",
    "easiest version control system", "simplest git workflow", "version control setup",
    "set up version control small team", "version control for remote teams",
    "remote team version control", "distributed version control", "centralized version control",
    "version control security", "secure code repository", "private code repository",
    "version control for sensitive code", "version control conflict resolution",
    "merge conflict", "merge conflict resolution", "resolve merge conflict",
    "version control commit frequency", "how often to commit code",
    "version control for non-code files", "version control for documents",
    "version control for config files", "version control saves time",
    "version control saves money", "productivity gains version control",
    "team productivity version control", "version control ROI",
    "company without version control", "job without version control",
    "red flags no version control", "company not using git",
  ],

  // --- Git Specific ---
  git: [
    "git", "git tutorial", "git guide", "git for beginners", "git commands",
    "git workflow", "git branching", "git branch strategy", "git merge", "git rebase",
    "git commit", "git push", "git pull", "git clone", "git init", "git status",
    "git log", "git diff", "git stash", "git tag", "git release",
    "git remote", "git fetch", "git checkout", "git reset", "git revert",
    "git cherry-pick", "git bisect", "git blame", "git hooks", "git LFS",
    "git large file storage", "git submodules", "git subtree",
    "git vs SVN", "git vs mercurial", "git vs perforce", "git vs TFS",
    "SVN to git migration", "mercurial to git", "perforce to git",
    "git for windows", "git for mac", "git for linux",
    "gitflow", "trunk based development", "feature branch workflow",
    "github flow", "gitlab flow", "forking workflow",
    "git best practices", "git tips", "git tricks", "advanced git",
    "git internals", "git objects", "git index", "git staging area",
    "git HEAD", "git reflog", "git gc", "git pack",
    "git server", "bare git repository", "git hosting server",
    "self hosted git", "run your own git server", "git on linux server",
  ],

  // --- Source Code Management ---
  scm: [
    "source code management", "SCM", "source control management", "source control system",
    "source control software", "source control tool", "source control platform",
    "source control for teams", "source control workflow", "source control best practices",
    "code repository", "code repository hosting", "repository management",
    "repository platform", "code versioning", "code tracking", "code history",
    "code backup", "code recovery", "recover deleted code", "code rollback",
    "rollback code changes", "undo code changes", "code change history",
    "code audit trail", "code accountability", "who changed what in code",
    "track code changes", "monitor code changes", "code diff tool",
    "compare code versions", "code review tool", "code review platform",
    "peer code review", "pull request", "pull request review", "PR review",
    "code collaboration tool", "collaborative coding", "pair programming tool",
    "team coding platform", "shared code repository", "codebase management",
  ],

  // --- DevOps & CI/CD ---
  devops: [
    "devops", "devops platform", "devops tool", "devops workflow", "devops pipeline",
    "CI/CD", "continuous integration", "continuous deployment", "continuous delivery",
    "CI/CD pipeline", "build pipeline", "deployment pipeline", "release pipeline",
    "automated testing", "automated deployment", "deploy code", "code deployment",
    "release management", "release automation", "versioned releases", "software releases",
    "release notes", "changelog", "semantic versioning", "semver",
    "DevSecOps", "shift left security", "secure DevOps", "DevOps security",
    "infrastructure as code", "GitOps", "platform engineering",
    "deploy from git", "deploy on push", "auto deploy", "trigger deployment from commit",
    "github actions alternative", "CI/CD without github", "build automation",
    "jenkins alternative", "circle CI alternative", "travis CI alternative",
    "code quality gate", "linting in CI", "testing in CI", "test automation",
  ],

  // --- Collaboration & Team Workflow ---
  collaboration: [
    "team collaboration tool", "developer collaboration", "code collaboration",
    "collaborative development", "team software development", "agile development tool",
    "scrum tool", "kanban for developers", "issue tracking", "bug tracking",
    "issue management", "ticket system for developers", "project management for developers",
    "developer task management", "sprint planning tool", "backlog management",
    "feature request tracking", "bug report system", "software defect tracking",
    "anomaly tracking", "incident management for developers", "code review workflow",
    "review and approve code", "approve pull request", "merge request",
    "code owner review", "required review", "branch protection",
    "team onboarding", "developer onboarding", "new developer setup",
    "developer experience", "DX", "inner source", "innersource platform",
    "developer portal", "internal developer platform", "IDP",
    "wiki", "developer wiki", "team knowledge base", "technical documentation",
    "code documentation", "inline documentation", "readme", "readme generator",
  ],

  // --- Code Hosting & Repositories ---
  codeHosting: [
    "code hosting", "code hosting platform", "free code hosting", "private code hosting",
    "self hosted code hosting", "repository hosting", "git repository hosting",
    "free git hosting", "private git hosting", "unlimited repositories",
    "public repositories", "private repositories", "repository visibility",
    "repository permissions", "repository access control", "repository fork",
    "forking a repository", "clone a repository", "star a repository",
    "repository statistics", "repository insights", "commit history",
    "commit graph", "contribution graph", "activity feed", "repository feed",
    "code browser", "online code browser", "browse code online", "read code online",
    "view source code online", "code search", "search code", "search in repository",
    "find code snippet", "repository search", "code discovery",
    "repository topics", "repository tags", "repository labels",
    "repository language detection", "repository star count", "trending repositories",
    "popular repositories", "featured repositories", "repository showcase",
  ],

  // --- Security ---
  security: [
    "secure code repository", "repository security", "code security", "secure git",
    "access control repository", "role-based access control", "RBAC git",
    "repository permissions", "private repository", "repository authentication",
    "two factor auth git", "SSO git hosting", "enterprise security git",
    "audit log repository", "code compliance", "SOC2 code hosting",
    "GDPR compliant code hosting", "secure code review", "dependency scanning",
    "secret scanning", "code vulnerability scanning", "SAST", "static analysis",
    "supply chain security", "software bill of materials", "SBOM",
    "signed commits", "commit signing", "GPG signed commits", "SSH key authentication",
    "API token authentication", "bearer token", "JWT authentication",
    "repository firewall", "IP allowlist", "branch protection rules",
    "required status checks", "protected branch", "force push protection",
    "signed releases", "release integrity", "artifact signing",
  ],

  // --- Developer Tools & IDE ---
  developerTools: [
    "developer tools", "developer IDE", "code editor", "source code editor",
    "lightweight code editor", "fast code editor", "minimal code editor",
    "programmers text editor", "developer text editor", "IDE for developers",
    "IDE integration", "git IDE integration", "version control IDE plugin",
    "VS Code alternative", "sublime text alternative", "atom alternative",
    "neovim alternative", "vim alternative", "emacs alternative",
    "lua IDE", "lua plugin", "lua scripting editor", "extensible editor",
    "code editor plugin", "editor extension", "editor customization",
    "terminal in editor", "integrated terminal", "built-in terminal",
    "git terminal", "command line git", "git command line tool",
    "git CLI", "git GUI", "git desktop client",
    "developer productivity tool", "productivity for programmers",
    "code editor speed", "fast IDE", "low latency editor",
    "offline development", "local first development", "local-first app",
  ],

  // --- Industry & Use Cases ---
  useCases: [
    "version control for web developers", "version control for backend developers",
    "version control for frontend developers", "version control for full stack developers",
    "version control for mobile developers", "version control for iOS developers",
    "version control for Android developers", "version control for Python developers",
    "version control for JavaScript developers", "version control for TypeScript developers",
    "version control for Java developers", "version control for C++ developers",
    "version control for C# developers", "version control for Rust developers",
    "version control for Go developers", "version control for Ruby developers",
    "version control for PHP developers", "version control for Swift developers",
    "version control for Kotlin developers", "version control for Lua developers",
    "version control for data science", "version control for machine learning",
    "version control for AI projects", "version control for notebooks",
    "jupyter notebook version control", "data pipeline version control",
    "version control for game development", "game dev source control",
    "unreal engine version control", "unity version control",
    "version control for indie games", "version control for game assets",
    "version control for design files", "figma version control",
    "version control for CAD files", "version control for 3D models",
    "version control for video production", "video project version control",
    "version control for marketing teams", "version control for content teams",
    "version control for writers", "version control for documentation",
    "version control for legal documents", "version control for contracts",
    "version control for configuration", "config file version control",
    "dotfiles version control", "environment config versioning",
    "infrastructure version control", "terraform version control",
    "ansible version control", "kubernetes manifest version control",
  ],

  // --- Enterprise & Teams ---
  enterprise: [
    "enterprise git", "enterprise source control", "enterprise code hosting",
    "enterprise developer platform", "enterprise DevOps", "enterprise repository",
    "enterprise code review", "enterprise CI/CD", "enterprise release management",
    "on-premise git", "on-prem code hosting", "self-hosted enterprise git",
    "air-gapped git", "disconnected git", "offline code hosting",
    "enterprise SSO", "SAML git", "LDAP git", "Active Directory git",
    "enterprise audit", "compliance code hosting", "regulated industry git",
    "financial services git", "healthcare git", "government git",
    "team size version control", "large team code hosting", "100 developer team git",
    "1000 developer team git", "monorepo", "monorepo hosting", "multi-repo",
    "polyrepo", "repository organization", "organization repositories",
    "team repositories", "cross-team collaboration", "inner-source",
  ],

  // --- Career & Learning ---
  career: [
    "learn git", "git for beginners", "git course", "git certification",
    "git bootcamp", "coding bootcamp git", "learn version control",
    "git tutorial for beginners", "git crash course", "git quick start",
    "git cheat sheet", "git commands cheat sheet", "git workflow cheat sheet",
    "version control interview questions", "git interview questions",
    "git for resume", "git skills for job", "developer skills 2025",
    "junior developer version control", "senior developer git skills",
    "software engineer version control", "devops engineer git skills",
    "SRE git", "platform engineer git", "backend developer git",
    "frontend developer git", "full stack git", "career version control",
    "get hired with git skills", "git job requirement", "git career importance",
    "open source contribution", "contribute to open source", "open source git",
    "first contribution", "good first issue", "hacktoberfest",
    "open source portfolio", "github portfolio", "developer portfolio",
    "coding portfolio", "show your code", "code showcase",
  ],

  // --- Specific Feature Keywords ---
  features: [
    "pull request", "pull request review", "PR workflow", "code review pull request",
    "branch management", "branch strategy", "branching model", "git flow",
    "merge strategy", "merge policy", "squash merge", "rebase merge",
    "commit message convention", "conventional commits", "commit history",
    "git blame", "who wrote this code", "code attribution",
    "release management", "tag release", "release notes generator",
    "changelog generator", "semantic release", "version tagging",
    "issue tracker", "bug tracker", "feature tracker", "milestone tracking",
    "project board", "kanban board for code", "sprint board developer",
    "wiki documentation", "team wiki", "project wiki", "technical wiki",
    "code snippets", "gist", "code paste", "share code snippet",
    "code search", "semantic code search", "full text code search",
    "repository insights", "code analytics", "contributor analytics",
    "commit frequency", "code churn", "bus factor", "code ownership",
    "repository templates", "project template", "starter template",
    "organization management", "team management", "member permissions",
    "repository webhooks", "git webhooks", "event driven git",
    "API access", "git API", "REST API code hosting", "GraphQL git API",
  ],

  // --- Programming Languages ---
  programmingLanguages: [
    "JavaScript version control", "TypeScript version control", "Python version control",
    "Java version control", "C++ version control", "C# version control", "Go version control",
    "Rust version control", "Ruby version control", "PHP version control", "Swift version control",
    "Kotlin version control", "Dart version control", "Scala version control", "Haskell version control",
    "Elixir version control", "Clojure version control", "Lua version control", "R version control",
    "MATLAB version control", "Perl version control", "Bash version control", "Shell version control",
    "PowerShell version control", "SQL version control", "HTML version control", "CSS version control",
    "SCSS version control", "Less version control", "Markdown version control",
    "JavaScript git workflow", "TypeScript monorepo", "Python project git", "Java git branching",
    "C++ git large files", "Go module versioning", "Rust cargo git", "Ruby on Rails git",
    "PHP composer git", "Swift package manager git", "Kotlin gradle git", "Dart pub git",
    "React version control", "Vue version control", "Angular version control", "Svelte version control",
    "Next.js version control", "Nuxt version control", "Remix version control", "Astro version control",
    "Node.js version control", "Deno version control", "Bun version control",
    "Django version control", "Flask version control", "FastAPI version control",
    "Spring Boot version control", "Laravel version control", "Rails version control",
    "Express version control", "NestJS version control", "Fastify version control",
  ],

  // --- Cloud & Infrastructure ---
  cloud: [
    "git on AWS", "git on Azure", "git on GCP", "git on DigitalOcean", "git on Linode",
    "git on Render", "git on Railway", "git on Fly.io", "git on Heroku",
    "AWS CodeCommit alternative", "Azure Repos alternative", "Google Cloud Source Repositories alternative",
    "self hosted git AWS", "self hosted git Azure", "self hosted git VPS",
    "git docker", "git kubernetes", "git terraform", "git ansible", "git helm",
    "gitops workflow", "gitops kubernetes", "gitops argocd", "gitops flux",
    "cloud native development", "cloud native git", "serverless version control",
    "git S3 backup", "git object storage", "git artifact storage",
    "multi cloud git", "hybrid cloud git", "private cloud git", "public cloud git",
    "cloud code repository", "cloud developer platform", "cloud IDE", "cloud9 alternative",
    "codespaces alternative", "github codespaces alternative", "gitpod alternative",
    "remote development environment", "cloud development environment", "CDE",
    "dev container", "development container", "devcontainer git",
    "docker compose git", "microservices version control", "monorepo microservices",
    "service mesh git", "API gateway git", "serverless functions git",
  ],

  // --- Open Source ---
  openSource: [
    "open source code hosting", "open source repository", "open source project management",
    "open source git hosting", "open source github alternative", "open source gitlab alternative",
    "open source gitea", "open source forgejo", "open source gogs",
    "free open source code hosting", "self hosted open source git",
    "open source contribution", "open source community", "open source collaboration",
    "open source license", "MIT license", "Apache license", "GPL license", "BSD license",
    "open source pull request", "open source code review", "open source issue tracker",
    "open source project hosting", "open source developer tools",
    "contributing to open source", "first open source contribution", "open source beginner",
    "open source for students", "open source for companies", "open source governance",
    "open source security", "open source supply chain", "open source SBOM",
    "open source maintainer", "open source sustainability", "open source funding",
    "hacktoberfest project", "google summer of code", "outreachy project",
    "open source portfolio", "build open source portfolio", "open source resume",
    "open source community building", "open source roadmap", "open source releases",
    "open source changelog", "open source documentation", "open source wiki",
  ],

  // --- Job Titles & Roles ---
  jobTitles: [
    "software engineer git", "software developer git", "frontend developer git",
    "backend developer git", "full stack developer git", "DevOps engineer git",
    "SRE git", "platform engineer git", "cloud engineer git", "data engineer git",
    "ML engineer git", "AI engineer git", "mobile developer git", "iOS developer git",
    "Android developer git", "game developer git", "embedded developer git",
    "security engineer git", "QA engineer git", "test engineer git",
    "release engineer git", "build engineer git", "infrastructure engineer git",
    "solutions architect git", "technical lead git", "engineering manager git",
    "CTO git", "VP engineering git", "principal engineer git", "staff engineer git",
    "senior engineer git", "junior engineer git", "engineering intern git",
    "freelance developer git", "contractor developer git", "consultant developer git",
    "open source developer git", "indie developer git", "solo developer git",
    "startup developer git", "enterprise developer git", "agency developer git",
    "product manager git", "technical product manager git", "scrum master git",
    "agile coach git", "project manager developer tools", "tech lead tools",
    "developer advocate git", "developer relations git", "developer evangelist git",
  ],

  // --- Long-tail Question Keywords ---
  longTail: [
    "how to set up git for a team", "how to use git for the first time",
    "how to create a repository", "how to push code to remote repository",
    "how to resolve a merge conflict", "how to create a pull request",
    "how to review a pull request", "how to fork a repository",
    "how to clone a repository", "how to create a branch in git",
    "how to merge branches in git", "how to rebase in git",
    "how to revert a commit in git", "how to undo a commit in git",
    "how to stash changes in git", "how to tag a release in git",
    "how to create a release", "how to write a commit message",
    "how to squash commits", "how to cherry-pick a commit",
    "how to set up git SSH", "how to authenticate with git",
    "how to set up git on Windows", "how to set up git on Mac",
    "how to set up git on Linux", "how to configure git user",
    "how to ignore files in git", "how to use gitignore",
    "how to track large files in git", "how to use git LFS",
    "how to back up a git repository", "how to restore deleted files in git",
    "how to find who changed a line in git", "how to see git history",
    "how to search in git log", "how to compare two branches",
    "how to see what changed in a commit", "how to undo pushed commits",
    "how to force push safely", "how to protect a branch",
    "how to require code reviews", "how to set up branch protection",
    "how to automate git workflows", "how to use git hooks",
    "how to integrate git with CI/CD", "how to deploy from git",
    "how to use git with Docker", "how to version control databases",
    "best way to organize repositories", "should I use monorepo or polyrepo",
    "when to create a new branch", "what is the best git workflow",
    "what is trunk based development", "what is gitflow", "what is git rebase vs merge",
    "why is my git push rejected", "why did my merge fail", "git push permission denied",
    "what does detached HEAD mean in git", "how to exit detached HEAD state",
    "git reset vs revert vs checkout", "git fetch vs pull", "git merge vs rebase",
    "git add vs git commit", "git origin vs upstream", "what is origin in git",
    "difference between git and github", "is github free", "github pricing",
    "github vs gitlab pricing", "github vs bitbucket pricing", "free unlimited repositories",
    "best free git hosting", "cheapest git hosting", "free private repositories",
    "unlimited private repos free", "free code collaboration tool",
    "free issue tracker for developers", "free project management for developers",
    "best tools for open source projects", "best tools for startups",
    "best tools for solo developers", "best tools for freelance developers",
    "best tools for remote teams", "best tools for distributed teams",
    "best tools for async development", "best tools for code collaboration",
  ],

  // --- Comparisons & Versus ---
  comparisons: [
    "NexusVault vs GitHub", "NexusVault vs GitLab", "NexusVault vs Bitbucket",
    "NexusVault vs Gitea", "NexusVault vs Forgejo", "NexusVault vs Gogs",
    "NexusVault vs Azure DevOps", "NexusVault vs AWS CodeCommit",
    "NexusVault vs SourceForge", "NexusVault vs Codeberg",
    "GitHub vs GitLab", "GitHub vs Bitbucket", "GitHub vs Azure DevOps",
    "GitHub vs Gitea", "GitHub vs SourceForge", "GitHub vs Codeberg",
    "GitLab vs Bitbucket", "GitLab vs Azure DevOps", "GitLab vs Gitea",
    "Bitbucket vs Azure DevOps", "Bitbucket vs Gitea",
    "git vs SVN", "git vs Mercurial", "git vs Perforce", "git vs TFS",
    "git vs CVS", "git vs TFVC", "git vs Plastic SCM",
    "GitHub Free vs GitHub Pro", "GitHub vs GitHub Enterprise",
    "GitLab Free vs GitLab Premium", "GitLab SaaS vs GitLab Self-Managed",
    "Bitbucket Cloud vs Bitbucket Server", "Bitbucket vs Jira",
    "GitHub Actions vs GitLab CI", "GitHub Actions vs Jenkins",
    "GitHub Actions vs CircleCI", "GitHub Actions vs TravisCI",
    "GitHub Copilot vs other AI coding tools", "AI code review tools",
    "best code review tool 2025", "best pull request tool 2025",
    "best issue tracker 2025", "best CI/CD tool 2025",
    "best developer platform 2025", "best code hosting 2025",
    "best repository manager 2025", "best git client 2025",
    "best git GUI 2025", "best git workflow 2025",
  ],

  // --- Performance & Scalability ---
  performance: [
    "high performance git", "scalable git hosting", "fast code repository",
    "low latency code hosting", "high availability git", "git server clustering",
    "git load balancing", "git horizontal scaling", "git database optimization",
    "git caching", "git CDN", "git compression", "git performance tuning",
    "large repository performance", "big monorepo performance", "git at scale",
    "git for large teams", "git for 1000 developers", "enterprise git performance",
    "git server hardware requirements", "git server capacity planning",
    "git replication", "git disaster recovery", "git high availability",
    "git backup strategy", "git redundancy", "git failover",
    "git read replica", "git write replica", "git database clustering",
    "git connection pooling", "git request queuing", "git rate limiting",
    "git API performance", "git webhook performance", "git CI performance",
    "fast pull request", "fast code review", "fast merge", "fast deploy",
    "sub second repository load", "instant code search", "fast diff rendering",
    "real time collaboration code", "live code collaboration",
    "concurrent developer support", "100 concurrent users git",
    "1000 concurrent users git", "10000 concurrent users git",
  ],

  // --- Specific Workflows ---
  workflows: [
    "trunk based development", "feature flag development", "blue green deployment",
    "canary deployment", "rolling deployment", "gitops deployment",
    "release branching strategy", "hotfix workflow", "patch workflow",
    "sprint workflow git", "agile git workflow", "scrum git workflow",
    "kanban git workflow", "continuous deployment workflow", "continuous delivery workflow",
    "feature branch workflow", "GitHub flow", "GitLab flow", "gitflow workflow",
    "forking workflow", "centralized workflow", "integration manager workflow",
    "dictator lieutenants workflow", "rebase workflow", "merge workflow",
    "squash merge workflow", "fast forward merge", "three way merge",
    "code freeze workflow", "release candidate workflow", "alpha beta release",
    "semantic release workflow", "conventional commits workflow",
    "automated changelog workflow", "tag and release workflow",
    "dependency update workflow", "security patch workflow", "vulnerability fix workflow",
    "hotfix branch workflow", "emergency fix workflow", "rollback workflow",
    "database migration workflow", "schema migration version control",
    "infrastructure change workflow", "config change workflow",
    "documentation workflow", "wiki workflow", "README workflow",
    "code review workflow", "review and approve workflow", "LGTM workflow",
    "pair programming workflow", "mob programming workflow",
    "inner source workflow", "open source contribution workflow",
    "fork and pull workflow", "upstream sync workflow",
  ],

  // --- Tutorials & Learning Content ---
  tutorials: [
    "git tutorial", "git beginner tutorial", "git intermediate tutorial", "git advanced tutorial",
    "git crash course", "git quick start", "git in 10 minutes", "git in 30 minutes",
    "learn git fast", "git for absolute beginners", "git zero to hero",
    "git hands on tutorial", "git practical guide", "git real world examples",
    "git cheat sheet", "git commands reference", "git quick reference",
    "git glossary", "git terminology", "git concepts explained",
    "git internals explained", "git plumbing commands", "git porcelain commands",
    "git objects explained", "git pack files", "git refspec",
    "git remote tracking branches", "git upstream downstream",
    "git HEAD explained", "git index explained", "git working tree explained",
    "git staging area explained", "git three areas",
    "version control course", "version control certification", "version control bootcamp",
    "source control tutorial", "DevOps tutorial", "CI/CD tutorial",
    "code review tutorial", "pull request tutorial", "branch strategy tutorial",
    "gitflow tutorial", "trunk based development tutorial",
    "git for data science tutorial", "git for machine learning tutorial",
    "git for game development tutorial", "git for designers tutorial",
    "git for writers tutorial", "git for managers tutorial",
    "git team setup tutorial", "git onboarding guide", "git best practices guide",
    "how companies use git", "how startups use git", "how enterprises use git",
    "git case study", "git success story", "git migration guide",
    "SVN to git tutorial", "Mercurial to git tutorial", "TFVC to git tutorial",
    "Perforce to git tutorial", "from no version control to git",
  ],

  // --- Specific Features Deep Dive ---
  featureDeepDive: [
    "repository forking", "fork vs clone", "when to fork a repo",
    "branch protection rules", "required status checks", "require pull request reviews",
    "code owners file", "CODEOWNERS", "auto assign reviewers",
    "pull request templates", "issue templates", "contributing guidelines",
    "repository templates", "project templates", "starter projects",
    "release drafts", "pre-release", "release assets", "release attachments",
    "repository insights", "contributor graphs", "commit activity graph",
    "code frequency graph", "punch card graph", "traffic analytics",
    "clones analytics", "views analytics", "referrers analytics",
    "dependency graph", "dependency alerts", "security advisories",
    "Dependabot alternative", "automated dependency updates",
    "repository topics", "repository tags", "repository labels",
    "milestone tracking", "project boards", "kanban boards",
    "automated project board", "issue to PR linking", "closing issues with PRs",
    "draft pull request", "WIP pull request", "ready for review PR",
    "PR checks", "status checks", "CI status on PR",
    "PR merge button", "squash and merge", "rebase and merge", "create a merge commit",
    "repository webhooks", "webhook payload", "webhook secret",
    "deploy keys", "personal access tokens", "OAuth apps", "GitHub Apps alternative",
    "repository secrets", "environment secrets", "secrets management",
    "repository variables", "environment variables in CI",
    "packages registry", "container registry", "npm registry",
    "PyPI alternative", "crates.io alternative", "package hosting",
    "repository pages", "documentation hosting", "static site from repo",
    "repository README", "profile README", "organization README",
    "README badges", "status badges", "build status badge", "coverage badge",
    "social preview image", "repository cover image", "repository banner",
    "archived repository", "readonly repository", "deprecated repository",
    "repository transfer", "repository rename", "repository visibility change",
    "repository deletion", "repository restore", "repository backup",
    "repository import", "repository export", "repository migration",
    "bulk repository operations", "organization repository management",
    "team repository access", "repository permission levels",
    "read access", "write access", "admin access", "maintain access", "triage access",
  ],

  // --- Geographic & Language Variants ---
  geographic: [
    "code hosting India", "developer platform India", "git hosting India",
    "code hosting UK", "developer platform UK", "git hosting UK",
    "code hosting Germany", "developer platform Germany", "git hosting Germany",
    "code hosting Canada", "developer platform Canada", "git hosting Canada",
    "code hosting Australia", "developer platform Australia", "git hosting Australia",
    "code hosting Brazil", "developer platform Brazil", "git hosting Brazil",
    "code hosting Japan", "developer platform Japan", "git hosting Japan",
    "code hosting China", "developer platform China", "git hosting China",
    "code hosting France", "developer platform France", "git hosting France",
    "code hosting Singapore", "developer platform Singapore",
    "best developer platform Asia", "best developer platform Europe",
    "best developer platform Americas", "best developer platform Africa",
    "free code hosting worldwide", "international developer platform",
    "multilingual code hosting", "localized developer platform",
    "GDPR compliant git hosting", "EU data residency git",
    "data sovereignty git", "regional git hosting", "local git hosting",
  ],

  // --- Business & Pricing ---
  business: [
    "free code hosting", "free git hosting", "free developer platform",
    "free private repositories", "free unlimited repositories",
    "free issue tracker", "free wiki", "free CI/CD",
    "cheap code hosting", "affordable git hosting", "low cost developer platform",
    "github pricing alternative", "gitlab pricing alternative", "bitbucket pricing alternative",
    "pay per user developer platform", "per seat licensing git",
    "flat rate git hosting", "unlimited users git hosting",
    "open source git pricing", "free tier git hosting", "freemium developer platform",
    "enterprise git pricing", "enterprise source control cost",
    "ROI of version control", "cost of not using version control",
    "developer tool cost comparison", "source control cost analysis",
    "budget developer tools", "cost effective developer platform",
    "small business developer tools", "SME developer platform",
    "startup developer tools", "startup git hosting",
    "non-profit developer tools", "NGO code hosting", "charity code hosting",
    "educational institution git", "university git hosting", "student developer platform",
    "government code hosting", "public sector git", "open government code",
    "white label git hosting", "branded developer platform", "custom domain git hosting",
    "git hosting reseller", "managed git service", "git as a service",
    "SaaS git hosting", "PaaS git", "IaaS git", "DBaaS for git",
  ],

  // --- Trending & Modern Concepts ---
  trending: [
    "AI code review", "AI pull request review", "AI commit messages",
    "AI code suggestions", "AI pair programming", "LLM code assistant",
    "copilot alternative", "AI developer tools 2025", "ML in developer workflows",
    "code intelligence", "semantic code search", "AI powered search code",
    "natural language code search", "code Q&A", "ask questions about code",
    "code explanation AI", "AI documentation generator", "AI README generator",
    "AI changelog generator", "AI release notes", "automated code review",
    "static analysis tool", "code quality tool", "technical debt tracking",
    "code coverage tracking", "test coverage in git", "test report in PR",
    "security scanning in CI", "SAST in pipeline", "DAST in pipeline",
    "supply chain attack prevention", "dependency confusion prevention",
    "software composition analysis", "SCA tool", "license compliance tool",
    "FOSS compliance", "open source license checker", "license scanning",
    "vulnerability database", "CVE tracking", "security advisory",
    "responsible disclosure", "bug bounty program", "security researcher",
    "web3 developer tools", "blockchain git", "decentralized code hosting",
    "IPFS code hosting", "peer to peer git", "distributed git hosting",
    "offline first development", "local first software", "offline git",
    "edge computing developer tools", "edge deployment git",
    "real time collaboration", "multiplayer code editor", "live coding",
    "low code developer platform", "no code version control",
    "visual git", "git visualization", "interactive git history",
    "3D git visualization", "git network graph", "repository analytics dashboard",
  ],

  // --- Integrations & Ecosystem ---
  integrations: [
    "git Slack integration", "git Discord integration", "git Teams integration",
    "git JIRA integration", "git Linear integration", "git Trello integration",
    "git Asana integration", "git Monday integration", "git Notion integration",
    "git Confluence integration", "git Zendesk integration", "git PagerDuty integration",
    "git Datadog integration", "git New Relic integration", "git Sentry integration",
    "git VS Code integration", "git JetBrains integration", "git IntelliJ integration",
    "git PyCharm integration", "git WebStorm integration", "git Rider integration",
    "git Eclipse integration", "git NetBeans integration", "git Xcode integration",
    "git Android Studio integration", "git Vim integration", "git Neovim integration",
    "git Emacs integration", "git Sublime Text integration",
    "git Jenkins integration", "git CircleCI integration", "git TravisCI integration",
    "git GitHub Actions integration", "git GitLab CI integration",
    "git ArgoCD integration", "git FluxCD integration", "git Spinnaker integration",
    "git Terraform integration", "git Ansible integration", "git Chef integration",
    "git Puppet integration", "git Kubernetes integration", "git Helm integration",
    "git Docker integration", "git Podman integration", "git BuildKit integration",
    "git SonarQube integration", "git Codecov integration", "git Coveralls integration",
    "git Snyk integration", "git Dependabot alternative", "git Renovate integration",
    "git npm integration", "git yarn integration", "git pnpm integration",
    "git pip integration", "git poetry integration", "git cargo integration",
    "git composer integration", "git maven integration", "git gradle integration",
    "git nuget integration", "git bundler integration", "git pub integration",
    "git Zapier integration", "git Make integration", "git n8n integration",
    "webhook receiver", "git event consumer", "git notification system",
    "git email notifications", "git SMS notifications", "git push notifications",
    "git activity feed", "git news feed", "git timeline",
    "SSO integration git", "SAML 2.0 git", "OpenID Connect git", "OAuth2 git",
    "LDAP integration git", "Active Directory git", "Okta git integration",
    "Auth0 git integration", "Clerk git integration", "Supabase git integration",
  ],

  // --- Platform Specific ---
  platform: [
    "git on Windows", "git Windows client", "git for Windows 11", "git Windows setup",
    "git on macOS", "git Mac client", "git for Mac M1", "git Mac setup",
    "git on Linux", "git Ubuntu", "git Debian", "git Fedora", "git Arch Linux",
    "git on Raspberry Pi", "git on ARM", "git on Android", "git on iOS",
    "git command line Windows", "git PowerShell", "git CMD", "git WSL",
    "git command line Mac", "git Terminal Mac", "git iTerm Mac",
    "git command line Linux", "git bash Linux", "git zsh Linux",
    "git GUI Windows", "git GUI Mac", "git GUI Linux",
    "GitHub Desktop alternative", "SourceTree alternative", "GitKraken alternative",
    "Fork git client alternative", "Tower git client alternative",
    "SmartGit alternative", "Sublime Merge alternative",
    "git browser extension", "git Chrome extension", "git Firefox extension",
    "git web interface", "git web client", "git browser client",
    "git mobile app", "git Android app", "git iOS app",
    "git terminal emulator", "git TUI", "git ncurses", "lazygit alternative",
    "tig alternative", "gitui alternative", "git terminal UI",
    "git shell prompt", "git bash prompt", "zsh git prompt", "oh my zsh git",
    "starship git integration", "powerlevel10k git",
  ],

};

// Build a flat, deduplicated keyword string for a given set of categories
export function buildKeywords(...categories: (keyof typeof SEO_KEYWORDS)[]): string {
  const all = new Set<string>();
  categories.forEach(cat => SEO_KEYWORDS[cat].forEach(k => all.add(k)));
  return Array.from(all).join(", ");
}

// Default keyword string for general pages (all categories)
export const DEFAULT_KEYWORDS = buildKeywords(
  "brand", "githubAlternative", "versionControl", "git", "scm",
  "codeHosting", "collaboration", "features", "security",
  "devops", "developerTools", "useCases", "enterprise", "career",
  "programmingLanguages", "cloud", "openSource", "longTail",
  "comparisons", "performance", "workflows", "tutorials",
  "featureDeepDive", "business", "trending", "integrations", "platform"
);

// Repository page keywords
export const REPO_KEYWORDS = buildKeywords(
  "brand", "githubAlternative", "codeHosting", "git", "features",
  "security", "devops", "collaboration", "featureDeepDive",
  "workflows", "performance", "integrations", "programmingLanguages"
);

// Profile page keywords
export const PROFILE_KEYWORDS = buildKeywords(
  "brand", "career", "collaboration", "codeHosting", "features",
  "openSource", "jobTitles", "tutorials"
);

// Search page keywords
export const SEARCH_KEYWORDS = buildKeywords(
  "brand", "githubAlternative", "versionControl", "codeHosting",
  "features", "useCases", "comparisons", "longTail", "geographic", "business"
);
