"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _home_view from './home-view.bones.json'

registerBones({
  "home-view": _home_view,
})
